/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Barack
 */
export interface Barack {
    /**
     * 
     * @type {number}
     * @memberof Barack
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Barack
     */
    city?: any;
    /**
     * 
     * @type {string}
     * @memberof Barack
     */
    state?: any;
    /**
     * 
     * @type {string}
     * @memberof Barack
     */
    postalCode?: any;
    /**
     * 
     * @type {string}
     * @memberof Barack
     */
    country?: any;
    /**
     * 
     * @type {string}
     * @memberof Barack
     */
    street?: any;
}
