/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ExhaustLevel
 */
export interface ExhaustLevel {
    /**
     * 
     * @type {number}
     * @memberof ExhaustLevel
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof ExhaustLevel
     */
    label?: any;
    /**
     * 
     * @type {number}
     * @memberof ExhaustLevel
     */
    value?: any;
}
