/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface StackTraceElement
 */
export interface StackTraceElement {
    /**
     * 
     * @type {string}
     * @memberof StackTraceElement
     */
    classLoaderName?: any;
    /**
     * 
     * @type {string}
     * @memberof StackTraceElement
     */
    moduleName?: any;
    /**
     * 
     * @type {string}
     * @memberof StackTraceElement
     */
    moduleVersion?: any;
    /**
     * 
     * @type {string}
     * @memberof StackTraceElement
     */
    methodName?: any;
    /**
     * 
     * @type {string}
     * @memberof StackTraceElement
     */
    fileName?: any;
    /**
     * 
     * @type {number}
     * @memberof StackTraceElement
     */
    lineNumber?: any;
    /**
     * 
     * @type {boolean}
     * @memberof StackTraceElement
     */
    nativeMethod?: any;
    /**
     * 
     * @type {string}
     * @memberof StackTraceElement
     */
    className?: any;
}
