/* tslint:disable */
/* eslint-disable */
/**
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TruckModel
 */
export interface TruckModel {
    /**
     * 
     * @type {LocationModel}
     * @memberof TruckModel
     */
    start?: any;
    /**
     * 
     * @type {number}
     * @memberof TruckModel
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof TruckModel
     */
    speed?: any;
}
