FROM node:14.15.4-slim

# Create app directory
WORKDIR /app

# Server
RUN mkdir -p /app
COPY build ./
COPY package.json ./package.json

RUN apk add --no-cache make gcc g++ python linux-headers udev
RUN npm install --only=production --build-from-source=serialport

# Setting environment variables
ENV LOG_FOLDER /app/logs
ENV NODE_ENV production

EXPOSE 8086

WORKDIR /app/back

CMD ["node", "app.js"]

