/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/fire-truck-api';
export * from './apis/fire-types-api';
export * from './apis/firemen-api';
export * from './apis/fires-api';
export * from './apis/resources-api';
export * from './apis/sensors-api';

