/*
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package project.grp3.emergency.core.api.truck.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import project.grp3.emergency.core.api.truck.model.LocationModel;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * LocationsModel
 */


public class LocationsModel {
  @SerializedName("start")
  private LocationModel start = null;

  @SerializedName("dest")
  private LocationModel dest = null;

  public LocationsModel start(LocationModel start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @Schema(description = "")
  public LocationModel getStart() {
    return start;
  }

  public void setStart(LocationModel start) {
    this.start = start;
  }

  public LocationsModel dest(LocationModel dest) {
    this.dest = dest;
    return this;
  }

   /**
   * Get dest
   * @return dest
  **/
  @Schema(description = "")
  public LocationModel getDest() {
    return dest;
  }

  public void setDest(LocationModel dest) {
    this.dest = dest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocationsModel locationsModel = (LocationsModel) o;
    return Objects.equals(this.start, locationsModel.start) &&
        Objects.equals(this.dest, locationsModel.dest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(start, dest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocationsModel {\n");
    
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    dest: ").append(toIndentedString(dest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}