/*
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package project.grp3.emergency.core.api.truck.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import project.grp3.emergency.core.api.truck.model.FiremanModel;
import project.grp3.emergency.core.api.truck.model.LocationModel;
import project.grp3.emergency.core.api.truck.model.TruckModel;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * MovementModel
 */


public class MovementModel {
  @SerializedName("trucks")
  private List<TruckModel> trucks = null;

  @SerializedName("firemen")
  private List<FiremanModel> firemen = null;

  @SerializedName("dest")
  private LocationModel dest = null;

  @SerializedName("resourceId")
  private BigDecimal resourceId = null;

  public MovementModel trucks(List<TruckModel> trucks) {
    this.trucks = trucks;
    return this;
  }

  public MovementModel addTrucksItem(TruckModel trucksItem) {
    if (this.trucks == null) {
      this.trucks = new ArrayList<>();
    }
    this.trucks.add(trucksItem);
    return this;
  }

   /**
   * Get trucks
   * @return trucks
  **/
  @Schema(description = "")
  public List<TruckModel> getTrucks() {
    return trucks;
  }

  public void setTrucks(List<TruckModel> trucks) {
    this.trucks = trucks;
  }

  public MovementModel firemen(List<FiremanModel> firemen) {
    this.firemen = firemen;
    return this;
  }

  public MovementModel addFiremenItem(FiremanModel firemenItem) {
    if (this.firemen == null) {
      this.firemen = new ArrayList<>();
    }
    this.firemen.add(firemenItem);
    return this;
  }

   /**
   * Get firemen
   * @return firemen
  **/
  @Schema(description = "")
  public List<FiremanModel> getFiremen() {
    return firemen;
  }

  public void setFiremen(List<FiremanModel> firemen) {
    this.firemen = firemen;
  }

  public MovementModel dest(LocationModel dest) {
    this.dest = dest;
    return this;
  }

   /**
   * Get dest
   * @return dest
  **/
  @Schema(description = "")
  public LocationModel getDest() {
    return dest;
  }

  public void setDest(LocationModel dest) {
    this.dest = dest;
  }

  public MovementModel resourceId(BigDecimal resourceId) {
    this.resourceId = resourceId;
    return this;
  }

   /**
   * Get resourceId
   * @return resourceId
  **/
  @Schema(description = "")
  public BigDecimal getResourceId() {
    return resourceId;
  }

  public void setResourceId(BigDecimal resourceId) {
    this.resourceId = resourceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MovementModel movementModel = (MovementModel) o;
    return Objects.equals(this.trucks, movementModel.trucks) &&
        Objects.equals(this.firemen, movementModel.firemen) &&
        Objects.equals(this.dest, movementModel.dest) &&
        Objects.equals(this.resourceId, movementModel.resourceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trucks, firemen, dest, resourceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MovementModel {\n");
    
    sb.append("    trucks: ").append(toIndentedString(trucks)).append("\n");
    sb.append("    firemen: ").append(toIndentedString(firemen)).append("\n");
    sb.append("    dest: ").append(toIndentedString(dest)).append("\n");
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}