/*
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package project.grp3.emergency.core.api.truck.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import project.grp3.emergency.core.api.truck.model.LocationModel;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * TruckModel
 */


public class TruckModel {
  @SerializedName("id")
  private BigDecimal id = null;

  @SerializedName("resourceId")
  private BigDecimal resourceId = null;

  @SerializedName("speed")
  private BigDecimal speed = null;

  @SerializedName("start")
  private LocationModel start = null;

  @SerializedName("dest")
  private LocationModel dest = null;

  @SerializedName("current")
  private LocationModel current = null;

  @SerializedName("travelState")
  private BigDecimal travelState = null;

  public TruckModel id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public TruckModel resourceId(BigDecimal resourceId) {
    this.resourceId = resourceId;
    return this;
  }

   /**
   * Get resourceId
   * @return resourceId
  **/
  @Schema(description = "")
  public BigDecimal getResourceId() {
    return resourceId;
  }

  public void setResourceId(BigDecimal resourceId) {
    this.resourceId = resourceId;
  }

  public TruckModel speed(BigDecimal speed) {
    this.speed = speed;
    return this;
  }

   /**
   * Get speed
   * @return speed
  **/
  @Schema(description = "")
  public BigDecimal getSpeed() {
    return speed;
  }

  public void setSpeed(BigDecimal speed) {
    this.speed = speed;
  }

  public TruckModel start(LocationModel start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @Schema(description = "")
  public LocationModel getStart() {
    return start;
  }

  public void setStart(LocationModel start) {
    this.start = start;
  }

  public TruckModel dest(LocationModel dest) {
    this.dest = dest;
    return this;
  }

   /**
   * Get dest
   * @return dest
  **/
  @Schema(description = "")
  public LocationModel getDest() {
    return dest;
  }

  public void setDest(LocationModel dest) {
    this.dest = dest;
  }

  public TruckModel current(LocationModel current) {
    this.current = current;
    return this;
  }

   /**
   * Get current
   * @return current
  **/
  @Schema(description = "")
  public LocationModel getCurrent() {
    return current;
  }

  public void setCurrent(LocationModel current) {
    this.current = current;
  }

  public TruckModel travelState(BigDecimal travelState) {
    this.travelState = travelState;
    return this;
  }

   /**
   * Get travelState
   * @return travelState
  **/
  @Schema(description = "")
  public BigDecimal getTravelState() {
    return travelState;
  }

  public void setTravelState(BigDecimal travelState) {
    this.travelState = travelState;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TruckModel truckModel = (TruckModel) o;
    return Objects.equals(this.id, truckModel.id) &&
        Objects.equals(this.resourceId, truckModel.resourceId) &&
        Objects.equals(this.speed, truckModel.speed) &&
        Objects.equals(this.start, truckModel.start) &&
        Objects.equals(this.dest, truckModel.dest) &&
        Objects.equals(this.current, truckModel.current) &&
        Objects.equals(this.travelState, truckModel.travelState);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, resourceId, speed, start, dest, current, travelState);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TruckModel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    speed: ").append(toIndentedString(speed)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    dest: ").append(toIndentedString(dest)).append("\n");
    sb.append("    current: ").append(toIndentedString(current)).append("\n");
    sb.append("    travelState: ").append(toIndentedString(travelState)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}