version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    ports:
      - 5434:5432
    container_name: emergency-manager-db

  manager:
    image: elyspio/cpe-s7-project:emergency-manager
    restart: always
    environment:
      DATABASE_PORT: 5434
    ports:
      - 8082:8080
    container_name: s7-project-emergency-manager-engine
