/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ExhaustLevelEntity
 */
export interface ExhaustLevelEntity {
    /**
     * 
     * @type {number}
     * @memberof ExhaustLevelEntity
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof ExhaustLevelEntity
     */
    label?: any;
    /**
     * 
     * @type {number}
     * @memberof ExhaustLevelEntity
     */
    value?: any;
    /**
     * 
     * @type {string}
     * @memberof ExhaustLevelEntity
     */
    coreId?: ExhaustLevelEntityCoreIdEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ExhaustLevelEntityCoreIdEnum {
    NONE = 'NONE',
    LOW = 'LOW',
    TIRED = 'TIRED',
    EXHAUSTED = 'EXHAUSTED',
    KO = 'KO'
}

