/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FireTruck
 */
export interface FireTruck {
    /**
     * 
     * @type {number}
     * @memberof FireTruck
     */
    barrackId?: any;
    /**
     * 
     * @type {TruckType}
     * @memberof FireTruck
     */
    type?: any;
    /**
     * 
     * @type {number}
     * @memberof FireTruck
     */
    id?: any;
}
