/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FireEntity
 */
export interface FireEntity {
    /**
     * 
     * @type {number}
     * @memberof FireEntity
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof FireEntity
     */
    detectionDate?: any;
    /**
     * 
     * @type {Date}
     * @memberof FireEntity
     */
    endDate?: any;
    /**
     * 
     * @type {FireTypeEntity}
     * @memberof FireEntity
     */
    type?: any;
    /**
     * 
     * @type {ResourceEntity}
     * @memberof FireEntity
     */
    resource?: any;
    /**
     * 
     * @type {SensorEntity}
     * @memberof FireEntity
     */
    sensor?: any;
}
