/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FiremanEntity
 */
export interface FiremanEntity {
    /**
     * 
     * @type {number}
     * @memberof FiremanEntity
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof FiremanEntity
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof FiremanEntity
     */
    lastname?: any;
    /**
     * 
     * @type {ExhaustLevelEntity}
     * @memberof FiremanEntity
     */
    exhaustLevel?: any;
    /**
     * 
     * @type {Array&lt;ResourceEntity&gt;}
     * @memberof FiremanEntity
     */
    resources?: any;
    /**
     * 
     * @type {BarrackEntity}
     * @memberof FiremanEntity
     */
    barrack?: any;
}
