/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Fireman
 */
export interface Fireman {
    /**
     * 
     * @type {number}
     * @memberof Fireman
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Fireman
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof Fireman
     */
    lastname?: any;
    /**
     * 
     * @type {ExhaustLevel}
     * @memberof Fireman
     */
    exhaustLevel?: any;
    /**
     * 
     * @type {number}
     * @memberof Fireman
     */
    barrackId?: any;
}
