/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ResourceEntity
 */
export interface ResourceEntity {
    /**
     * 
     * @type {number}
     * @memberof ResourceEntity
     */
    id?: any;
    /**
     * 
     * @type {FireEntity}
     * @memberof ResourceEntity
     */
    fire?: any;
    /**
     * 
     * @type {Array&lt;FiremanEntity&gt;}
     * @memberof ResourceEntity
     */
    firemen?: any;
    /**
     * 
     * @type {Array&lt;FireTruckEntity&gt;}
     * @memberof ResourceEntity
     */
    fireTrucks?: any;
    /**
     * 
     * @type {string}
     * @memberof ResourceEntity
     */
    travelState?: ResourceEntityTravelStateEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ResourceEntityTravelStateEnum {
    MOVING = 'MOVING',
    AVAILABLE = 'AVAILABLE'
}

