/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SdisEntity
 */
export interface SdisEntity {
    /**
     * 
     * @type {number}
     * @memberof SdisEntity
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof SdisEntity
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof SdisEntity
     */
    department?: any;
    /**
     * 
     * @type {Array&lt;BarrackEntity&gt;}
     * @memberof SdisEntity
     */
    barracks?: any;
}
