/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SensorEntity
 */
export interface SensorEntity {
    /**
     * 
     * @type {number}
     * @memberof SensorEntity
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof SensorEntity
     */
    city?: any;
    /**
     * 
     * @type {string}
     * @memberof SensorEntity
     */
    state?: any;
    /**
     * 
     * @type {string}
     * @memberof SensorEntity
     */
    postalCode?: any;
    /**
     * 
     * @type {string}
     * @memberof SensorEntity
     */
    country?: any;
    /**
     * 
     * @type {string}
     * @memberof SensorEntity
     */
    street?: any;
    /**
     * 
     * @type {Array&lt;FireEntity&gt;}
     * @memberof SensorEntity
     */
    fires?: any;
    /**
     * 
     * @type {Array&lt;FireTypeEntity&gt;}
     * @memberof SensorEntity
     */
    fireTypes?: any;
}
