/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TruckTypeEntity
 */
export interface TruckTypeEntity {
    /**
     * 
     * @type {number}
     * @memberof TruckTypeEntity
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof TruckTypeEntity
     */
    label?: any;
    /**
     * 
     * @type {number}
     * @memberof TruckTypeEntity
     */
    capacity?: any;
    /**
     * 
     * @type {number}
     * @memberof TruckTypeEntity
     */
    volume?: any;
    /**
     * 
     * @type {number}
     * @memberof TruckTypeEntity
     */
    speed?: any;
    /**
     * 
     * @type {Array&lt;FireTruckEntity&gt;}
     * @memberof TruckTypeEntity
     */
    fireTrucks?: any;
    /**
     * 
     * @type {Array&lt;FireTypeEntity&gt;}
     * @memberof TruckTypeEntity
     */
    fireTypes?: any;
}
