FROM node:14-alpine

# Create app directory

# Server
RUN mkdir -p /app/back


COPY build /app/back
COPY package.json /app/back/package.json
RUN cd /app/back && npm i --only=production

# Setting environment variables
ENV LOG_FOLDER /app/logs
ENV NODE_ENV production

WORKDIR /app/back

CMD ["node", "app.js"]

