FROM node:14-alpine

# Create app directory
WORKDIR /app

# Server
RUN mkdir -p /app/back
COPY build ./back
COPY package.json ./back/package.json
RUN cd back && npm i --only=production

# Setting environment variables
ENV LOG_FOLDER /app/logs
ENV NODE_ENV production

WORKDIR /app/back

CMD ["node", "app.js"]

