/* tslint:disable */
/* eslint-disable */
/**
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PostFireModel
 */
export interface PostFireModel {
    /**
     * 
     * @type {number}
     * @memberof PostFireModel
     */
    sensorId?: any;
    /**
     * 
     * @type {number}
     * @memberof PostFireModel
     */
    intensity?: any;
    /**
     * 
     * @type {number}
     * @memberof PostFireModel
     */
    fireTypeId?: any;
}
