/*
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package project.grp3.simulator.core.api.microbitsimulator.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * PostFireModel
 */


public class PostFireModel
{
    @SerializedName("sensorId")
    private BigDecimal sensorId = null;

    @SerializedName("intensity")
    private BigDecimal intensity = null;

    @SerializedName("fireTypeId")
    private BigDecimal fireTypeId = null;

    public PostFireModel sensorId(BigDecimal sensorId)
    {
        this.sensorId = sensorId;
        return this;
    }

    /**
     * Get sensorId
     *
     * @return sensorId
     **/
    @Schema(description = "")
    public BigDecimal getSensorId()
    {
        return sensorId;
    }

    public void setSensorId(BigDecimal sensorId)
    {
        this.sensorId = sensorId;
    }

    public PostFireModel intensity(BigDecimal intensity)
    {
        this.intensity = intensity;
        return this;
    }

    /**
     * Get intensity
     *
     * @return intensity
     **/
    @Schema(description = "")
    public BigDecimal getIntensity()
    {
        return intensity;
    }

    public void setIntensity(BigDecimal intensity)
    {
        this.intensity = intensity;
    }

    public PostFireModel fireTypeId(BigDecimal fireTypeId)
    {
        this.fireTypeId = fireTypeId;
        return this;
    }

    /**
     * Get fireTypeId
     *
     * @return fireTypeId
     **/
    @Schema(description = "")
    public BigDecimal getFireTypeId()
    {
        return fireTypeId;
    }

    public void setFireTypeId(BigDecimal fireTypeId)
    {
        this.fireTypeId = fireTypeId;
    }


    @Override
    public boolean equals(java.lang.Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        PostFireModel postFireModel = (PostFireModel) o;
        return Objects.equals(this.sensorId, postFireModel.sensorId) &&
                Objects.equals(this.intensity, postFireModel.intensity) &&
                Objects.equals(this.fireTypeId, postFireModel.fireTypeId);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(sensorId, intensity, fireTypeId);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class PostFireModel {\n");

        sb.append("    sensorId: ").append(toIndentedString(sensorId)).append("\n");
        sb.append("    intensity: ").append(toIndentedString(intensity)).append("\n");
        sb.append("    fireTypeId: ").append(toIndentedString(fireTypeId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}