/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package project.grp3.emergency.core.api.emergency.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Body
 */


public class Body {
  @SerializedName("sensorId")
  private Long sensorId = null;

  @SerializedName("intensity")
  private Integer intensity = null;

  @SerializedName("fireTypeId")
  private Long fireTypeId = null;

  public Body sensorId(Long sensorId) {
    this.sensorId = sensorId;
    return this;
  }

   /**
   * Get sensorId
   * @return sensorId
  **/
  @Schema(description = "")
  public Long getSensorId() {
    return sensorId;
  }

  public void setSensorId(Long sensorId) {
    this.sensorId = sensorId;
  }

  public Body intensity(Integer intensity) {
    this.intensity = intensity;
    return this;
  }

   /**
   * Get intensity
   * @return intensity
  **/
  @Schema(description = "")
  public Integer getIntensity() {
    return intensity;
  }

  public void setIntensity(Integer intensity) {
    this.intensity = intensity;
  }

  public Body fireTypeId(Long fireTypeId) {
    this.fireTypeId = fireTypeId;
    return this;
  }

   /**
   * Get fireTypeId
   * @return fireTypeId
  **/
  @Schema(description = "")
  public Long getFireTypeId() {
    return fireTypeId;
  }

  public void setFireTypeId(Long fireTypeId) {
    this.fireTypeId = fireTypeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body body = (Body) o;
    return Objects.equals(this.sensorId, body.sensorId) &&
        Objects.equals(this.intensity, body.intensity) &&
        Objects.equals(this.fireTypeId, body.fireTypeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sensorId, intensity, fireTypeId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body {\n");
    
    sb.append("    sensorId: ").append(toIndentedString(sensorId)).append("\n");
    sb.append("    intensity: ").append(toIndentedString(intensity)).append("\n");
    sb.append("    fireTypeId: ").append(toIndentedString(fireTypeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}