/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package project.grp3.simulator.core.api.emergency.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Body1
 */


public class Body1
{
    @SerializedName("ressourceId")
    private Long ressourceId = null;

    public Body1 ressourceId(Long ressourceId)
    {
        this.ressourceId = ressourceId;
        return this;
    }

    /**
     * Get ressourceId
     *
     * @return ressourceId
     **/
    @Schema(description = "")
    public Long getRessourceId()
    {
        return ressourceId;
    }

    public void setRessourceId(Long ressourceId)
    {
        this.ressourceId = ressourceId;
    }


    @Override
    public boolean equals(java.lang.Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        Body1 body1 = (Body1) o;
        return Objects.equals(this.ressourceId, body1.ressourceId);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(ressourceId);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class Body1 {\n");

        sb.append("    ressourceId: ").append(toIndentedString(ressourceId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}