/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package project.grp3.simulator.core.api.emergency.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * FireResourceNewFire
 */


public class FireResourceNewFire
{
    @SerializedName("sensorId")
    private Long sensorId = null;

    @SerializedName("intensity")
    private Integer intensity = null;

    @SerializedName("fireTypeId")
    private Long fireTypeId = null;

    public FireResourceNewFire sensorId(Long sensorId)
    {
        this.sensorId = sensorId;
        return this;
    }

    /**
     * Get sensorId
     *
     * @return sensorId
     **/
    @Schema(description = "")
    public Long getSensorId()
    {
        return sensorId;
    }

    public void setSensorId(Long sensorId)
    {
        this.sensorId = sensorId;
    }

    public FireResourceNewFire intensity(Integer intensity)
    {
        this.intensity = intensity;
        return this;
    }

    /**
     * Get intensity
     *
     * @return intensity
     **/
    @Schema(description = "")
    public Integer getIntensity()
    {
        return intensity;
    }

    public void setIntensity(Integer intensity)
    {
        this.intensity = intensity;
    }

    public FireResourceNewFire fireTypeId(Long fireTypeId)
    {
        this.fireTypeId = fireTypeId;
        return this;
    }

    /**
     * Get fireTypeId
     *
     * @return fireTypeId
     **/
    @Schema(description = "")
    public Long getFireTypeId()
    {
        return fireTypeId;
    }

    public void setFireTypeId(Long fireTypeId)
    {
        this.fireTypeId = fireTypeId;
    }


    @Override
    public boolean equals(java.lang.Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        FireResourceNewFire fireResourceNewFire = (FireResourceNewFire) o;
        return Objects.equals(this.sensorId, fireResourceNewFire.sensorId) &&
                Objects.equals(this.intensity, fireResourceNewFire.intensity) &&
                Objects.equals(this.fireTypeId, fireResourceNewFire.fireTypeId);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(sensorId, intensity, fireTypeId);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class FireResourceNewFire {\n");

        sb.append("    sensorId: ").append(toIndentedString(sensorId)).append("\n");
        sb.append("    intensity: ").append(toIndentedString(intensity)).append("\n");
        sb.append("    fireTypeId: ").append(toIndentedString(fireTypeId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}