/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package project.grp3.simulator.core.api.emergency.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ResourceGetResource
 */


public class ResourceGetResource
{
    @SerializedName("id")
    private Long id = null;

    @SerializedName("firemen")
    private List<Fireman> firemen = null;

    @SerializedName("trucks")
    private List<FireTruck> trucks = null;

    @SerializedName("baracks")
    private List<Barack> baracks = null;

    public ResourceGetResource id(Long id)
    {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public Long getId()
    {
        return id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    public ResourceGetResource firemen(List<Fireman> firemen)
    {
        this.firemen = firemen;
        return this;
    }

    public ResourceGetResource addFiremenItem(Fireman firemenItem)
    {
        if (this.firemen == null)
        {
            this.firemen = new ArrayList<>();
        }
        this.firemen.add(firemenItem);
        return this;
    }

    /**
     * Get firemen
     *
     * @return firemen
     **/
    @Schema(description = "")
    public List<Fireman> getFiremen()
    {
        return firemen;
    }

    public void setFiremen(List<Fireman> firemen)
    {
        this.firemen = firemen;
    }

    public ResourceGetResource trucks(List<FireTruck> trucks)
    {
        this.trucks = trucks;
        return this;
    }

    public ResourceGetResource addTrucksItem(FireTruck trucksItem)
    {
        if (this.trucks == null)
        {
            this.trucks = new ArrayList<>();
        }
        this.trucks.add(trucksItem);
        return this;
    }

    /**
     * Get trucks
     *
     * @return trucks
     **/
    @Schema(description = "")
    public List<FireTruck> getTrucks()
    {
        return trucks;
    }

    public void setTrucks(List<FireTruck> trucks)
    {
        this.trucks = trucks;
    }

    public ResourceGetResource baracks(List<Barack> baracks)
    {
        this.baracks = baracks;
        return this;
    }

    public ResourceGetResource addBaracksItem(Barack baracksItem)
    {
        if (this.baracks == null)
        {
            this.baracks = new ArrayList<>();
        }
        this.baracks.add(baracksItem);
        return this;
    }

    /**
     * Get baracks
     *
     * @return baracks
     **/
    @Schema(description = "")
    public List<Barack> getBaracks()
    {
        return baracks;
    }

    public void setBaracks(List<Barack> baracks)
    {
        this.baracks = baracks;
    }


    @Override
    public boolean equals(java.lang.Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        ResourceGetResource resourceGetResource = (ResourceGetResource) o;
        return Objects.equals(this.id, resourceGetResource.id) &&
                Objects.equals(this.firemen, resourceGetResource.firemen) &&
                Objects.equals(this.trucks, resourceGetResource.trucks) &&
                Objects.equals(this.baracks, resourceGetResource.baracks);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(id, firemen, trucks, baracks);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class ResourceGetResource {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    firemen: ").append(toIndentedString(firemen)).append("\n");
        sb.append("    trucks: ").append(toIndentedString(trucks)).append("\n");
        sb.append("    baracks: ").append(toIndentedString(baracks)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}