version: "3.1"
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DATABASE}
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    ports:
      - 5435:5432
    container_name: s7-project-truck-manager-db


  app:
    image: elyspio/cpe-s7-project:truck-manager
    environment:
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DATABASE: ${DATABASE_DATABASE}
      OWN_PORT: ${OWN_PORT}
      EMERGENCY_MANAGER_HOST: ${EMERGENCY_MANAGER_HOST}

    ports:
      - 8085:8085
    container_name: s7-project-truck-manager-app
