version: "3.1"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    ports:
      - 5435:5432
    container_name: s7-project-truck-manager-db


  app:
    image: elyspio/cpe-s7-project:truck-manager
    environment:
      DATABASE_PORT: 5435
      DATABASE_HOST: 192.168.0.44
      SERVER_HTTP_PORT: 8085
    ports:
      - 8085:8085
    container_name: s7-project-truck-manager-app
