/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ResourceGetResource
 */
export interface ResourceGetResource {
    /**
     * 
     * @type {number}
     * @memberof ResourceGetResource
     */
    id?: any;
    /**
     * 
     * @type {Array&lt;Fireman&gt;}
     * @memberof ResourceGetResource
     */
    firemen?: any;
    /**
     * 
     * @type {Array&lt;FireTruck&gt;}
     * @memberof ResourceGetResource
     */
    trucks?: any;
    /**
     * 
     * @type {Array&lt;Barack&gt;}
     * @memberof ResourceGetResource
     */
    baracks?: any;
}
